package com.learnDrools;

import com.secbro.drools.model.Person

rule "中文名称"
    when
        $p : Person(name == "zhangsan" || age == 18)
    then
        System.out.println("null-safe-test");
        System.out.println($p.getName());

end

rule "equals-test"
    when
        $p : Person(name == "zhangsan")
    then
        System.out.println("equals-test");
        System.out.println($p.getName());

end


rule "binding-test"

    lock-on-active

    when
        $p : Person(age == 18) //对象绑定只能绑定一个
    then
        System.out.println("binding-test");
        System.out.println($p.getAge());

end
