package com.insertDemo
import com.secbro.drools.model.Person

rule "insert-demo-rules-1"
 salience 2
when

then
    System.out.println("insert-demo-rules-1规则被触发");
    Person p = new Person();
    p.setAge(25);

    //执行了insert后，并不会再一次触发这个规则，这是和no-loop.drl中不同的
    insert(p);

end

rule "insert-demo-rules-2"
salience 1
//lock-on-active true
when
    $p : Person(age == 25)
then
    System.out.println("insert-demo-rules-2规则被触发");
    System.out.println("person.age=" + $p.getAge());

end